apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: people-ui:2.0.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      volumeMounts:
        - name: frontend-config-vol
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
  volumes:
    - name: frontend-config-vol
      configMap:
        name: frontend-config
