apiVersion: v1
kind: Pod
metadata:
  name: backend-nginx-pod
spec:
  containers:
  - name: backend
    image: people-api:1.0.0
    ports:
      - containerPort: 8080
    env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: ConnectionStrings__Default
          value: "Host=postgres-service;Port=5432;Database=people_db;Username=postgres;Password=postgres"

  - name: nginx
    image: nginx:alpine
    ports:
      - containerPort: 80
