apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  # The value here must be the Base64 encoded content of your password file
  # You can generate this using 'base64 -w 0 ./secrets/db-password.txt' on Linux/macOS
  # or 'certutil -encode ./secrets/db-password.txt temp.b64 && findstr /v "-*" temp.b64' on Windows
  db-password: cG9zdGdyZXM=
