apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:16-alpine
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: people_db
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD_FILE
          value: /etc/db-secrets/db-password
      volumeMounts:
        - name: db-secret
          mountPath: /etc/db-secrets
          readOnly: true
  volumes:
    - name: db-secret
      secret:
        secretName: db-password
